name: Build and Deploy Java App to Azure Web App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: SecurityDemo/build/libs/SecurityDemo-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Se asegura de que el build haya terminado antes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List files to verify path (opcional)
        run: ls -lh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E95D508A21BA4506A6BDDC469CBEE0D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BFA8E95BECB74E3AA25F87AF7B01E2FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66104967F20E418A9F4B40F16F3836C2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AuthenticationAPI'
          slot-name: 'Production'
          package: SecurityDemo-0.0.1-SNAPSHOT.jar
